// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var DMCast, cast;

  cast = window.cast || {};

  DMCast = (function() {
    DMCast.APPID = '358a5251-4f55-4e2d-9276-62da9b153a22_1';

    DMCast.PROTOCOL = 'ramp';

    function DMCast() {
      var castEvents;
      castEvents = cast.receiver.Channel.EventType;
      this.mChannelHandler = new cast.receiver.ChannelHandler('ramp');
      this.mChannelHandler.addEventListener(castEvents.MESSAGE, this.onMessage.bind(this));
      this.mChannelHandler.addEventListener(castEvents.OPEN, this.onChannelOpened.bind(this));
      this.mChannelHandler.addEventListener(castEvents.CLOSED, this.onChannelClosed.bind(this));
    }

    DMCast.prototype.onChannelOpened = function(event) {
      console.log('onChannelOpened. Total number of channels: ' + this.mChannelHandler.getChannels().length);
    };

    DMCast.prototype.onChannelClosed = function(event) {
      var clen;
      clen = this.mChannelHandler.getChannels().length;
      console.log('onChannelClosed. Total number of channels: ' + clen);
      if (clen === 0) {
        return window.close();
      }
    };

    DMCast.prototype.onMessage = function(event) {
      return console.log(event);
    };

    return DMCast;

  })();

  window.addEventListener('load', function() {
    var app, player, receiver;
    player = document.querySelector('.player');
    console.log(cast.receiver.platform.isReady());
    receiver = new cast.receiver.Receiver(DMCast.APPID, [DMCast.PROTOCOL]);
    app = new DMCast();
    app.mChannelHandler.addChannelFactory(receiver.createChannelFactory(DMCast.PROTOCOL));
    receiver.start();
  });

}).call(this);
