// Generated by CoffeeScript 1.6.3
(function() {
  DMCast.controller('MainCtrl', function($scope) {
    var channelFactory, player, receiver, remoteMedia;
    receiver = new cast.receiver.Receiver('358a5251-4f55-4e2d-9276-62da9b153a22', [cast.receiver.RemoteMedia.NAMESPACE], "", 5);
    remoteMedia = new cast.receiver.RemoteMedia();
    channelFactory = receiver.createChannelFactory(cast.receiver.RemoteMedia.NAMESPACE);
    remoteMedia.addChannelFactory(channelFactory);
    receiver.start();
    player = document.getElementById('player');
    remoteMedia.setMediaElement(player);
    return player.addEventListener('loadedmetadata', function() {
      $scope.videodata = [remoteMedia.getTitle, remoteMedia.getImageURL, remoteMedia.getContentInfo];
      return $scope.$apply();
    });
  });

}).call(this);
